### ISSUE TITLE
Roblox loads whatever property is last in the file rather than whichever one is newest

### ISSUE THREAD

**Issue by Dekkonot** [rojo-rbx/rbx-dom#329]
After some testing, our assumption made with property migrations is wrong. Rather than Roblox always choosing the newer of the two properties to load, they instead seem just take load whichever property is later in the file. This is simpler but it means that the way we implement migrations is incorrect and it's only worked because we've gotten lucky.

Specifically, as of the time of writing we have three migrations:
- `Font` to `FontFace`
- `IgnoreGuiInset` to `ScreenInsets`
- `BrickColor` to `Color`

When serializing properties, we sort them alphabetically by name to make sure the build is deterministic. Since in all three of these cases, the property we're migration **to** is after the one we're migration **from** alphabetically, there's been no issue. In the event that a migration is added that violates this rule though, it'll fail.

The easiest option for solving this is just to not serialize properties we have a migration for. This isn't good for projects like Lune however, so we'd need a more robust solution. To me, it feels like #277 is a valid solution here because it means we wouldn't have to worry about stripping properties (presumably migrated properties would be proxied by their migration destinations) but regardless, it's something to think about. It isn't an issue right now, so we have time.

**Comment by kennethloeffler** [comment]
Isn't this only a problem when the same instance contains both the old and the new property (which can only occur with a crafted file)?

**Comment by Dekkonot** [comment]
I'm not sure if it's even a real issue, but you mentioned in #328 that it might cause `BrickColor` to serialize and if that's the case, it's not out of the question that this could be a problem for us later. I'm not sure it's worth worrying about too much right now but it's something we should be aware of in case we add a migration where it could be a problem.

**Comment by kennethloeffler** [comment]
Sorry, I probably wasn't clear enough. It is possible to create this kind of inconsistency right now:

``` rust
fn main() {
    let properties = [
        ("brickColor", Variant::BrickColor(BrickColor::DarkIndigo)),
        ("BrickColor", Variant::BrickColor(BrickColor::BrightRed)),
        ("Color", Variant::Color3(Color3::new(0.0, 0.0, 0.0))),
    ];

    let dom = WeakDom::new(InstanceBuilder::new("ROOT").with_children([
        InstanceBuilder::new("Part").with_properties(properties.clone()),
        InstanceBuilder::new("Part").with_properties(properties.clone()),
        InstanceBuilder::new("Part").with_properties(properties.clone()),
    ]));

    let output = BufWriter::new(File::create("./output.rbxm").unwrap());
    let _ = to_writer(output, &dom, dom.root().children());
}
```
And some rbx-util output of the result:
``` yaml
---
num_types: 1
num_instances: 3
chunks:
  - Inst:
      type_id: 0
      type_name: Part
      object_format: 0
      referents:
        - 0
        - 1
        - 2
  - Prop:
      type_id: 0
      prop_name: BrickColor
      prop_type: BrickColor
      values:
        - 21
        - 21
        - 21
  - Prop:
      type_id: 0
      prop_name: Color3uint8
      prop_type: Color3uint8
      values:
        - - 0
          - 0
          - 0
        - - 0
          - 0
          - 0
        - - 0
          - 0
          - 0
  - Prop:
      type_id: 0
      prop_name: Name
      prop_type: String
      values:
        - Part
        - Part
        - Part
  - Prop:
      type_id: 0
      prop_name: brickColor
      prop_type: BrickColor
      values:
        - 308
        - 308
        - 308
  - Prnt:
      version: 0
      links:
        - - 0
          - -1
        - - 1
          - -1
        - - 2
          - -1
  - End
```
When this file is loaded in Roblox Studio, the parts end up with the color in the `brickColor` chunk, which is indeed the last chunk here. When rbx-dom reads this file, `brickColor` and `BrickColor` are migrated, and again, the final value depends on ordering.

> After some testing, our assumption made with property migrations is wrong. Rather than Roblox always choosing the newer of the two properties to load, they instead seem just take load whichever property is later in the file. This is simpler but it means that the way we implement migrations is incorrect and it's only worked because we've gotten lucky.

This problem is only possible by intentionally inserting these properties into the dom after deserialization, so I don't really see it as a fault in property migration (which only happens during deserialization).

> The easiest option for solving this is just to not serialize properties we have a migration for. This isn't good for projects like Lune however, so we'd need a more robust solution. To me, it feels like #277 is a valid solution here [...]

I agree with all this - migrated properties should not be serialized, it's just a question of when we should change it. The situation is probably better now than it was before (when using the `BrickColor` property would just cause errors), but if a user manages to create these inconsistencies, they're going to be pretty confused.

I think I'll start building a prototype for proxy properties this week - it's looking pretty important for correctness!
